name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: npm
          
      - name: Install dependencies
        run: npm install
        
      - name: Check linting
        run: npm run lint

      - name: Check tests
        run: npm run test:ci

      - name: Coveralls
        uses: coverallsapp/github-action@v2
