name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
